/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ec.edu.espol.workshops;

public class Library {
    public boolean someLibraryMethod() {
    	System.out.println("Hola Mundo");
        return true;
    }
}
