/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ec.edu.espol.workshops;
import static org.junit.Assert.*;
import org.junit.Test;

public class BranchCoverageTest {
	
	@Test public void testLIC01() {
   	 Cliente cliente = new Cliente(18,Sexo.Femenino,EstadoCivil.Casado);
	    Prima prima = new Prima(cliente);
		assertEquals(-1,prima.calcularPrima(false));
    }
	
	@Test public void testLIC02() {
    	Cliente cliente = new Cliente(18,Sexo.Femenino,EstadoCivil.Casado);
 	    Prima prima = new Prima(cliente);
 		assertEquals(300,prima.calcularPrima(true));
    }
	
	@Test public void testAGE01() {
	   	 Cliente cliente = new Cliente(80,Sexo.Femenino,EstadoCivil.Casado);
		    Prima prima = new Prima(cliente);
			assertEquals(-1,prima.calcularPrima(true));
	    }
		
	@Test public void testAGE02() {
    	Cliente cliente = new Cliente(79,Sexo.Femenino,EstadoCivil.Casado);
 	    Prima prima = new Prima(cliente);
 		assertEquals(300,prima.calcularPrima(true));
    }
	
	@Test public void testCMB01() {
	   	 Cliente cliente = new Cliente(18,Sexo.Femenino,EstadoCivil.Soltero);
		    Prima prima = new Prima(cliente);
			assertEquals(300,prima.calcularPrima(true));
	}
		
	@Test public void testCMB02() {
   	Cliente cliente = new Cliente(50,Sexo.Masculino,EstadoCivil.Soltero);
	    Prima prima = new Prima(cliente);
		assertEquals(400,prima.calcularPrima(true));
   }

	@Test 
	public void testCMB03() {
	   	 Cliente cliente = new Cliente(20,Sexo.Masculino,EstadoCivil.Soltero);
		    Prima prima = new Prima(cliente);
			assertEquals(2000,prima.calcularPrima(true));
    }

	@Test 
	public void testCMB04() {
	   	 Cliente cliente = new Cliente(20,Sexo.Masculino,EstadoCivil.Casado);
		    Prima prima = new Prima(cliente);
			assertEquals(300,prima.calcularPrima(true));
	}
	
	
}
