/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ec.edu.espol.workshops;
import static org.junit.Assert.*;
import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    	System.out.println("Hola Mundo");
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
